#!/usr/bin/env python3
import urllib.parse
body = urllib.parse.parse_qs(input())
ans = 0
if body["operator"][0] == "+":
    ans = float(body["before"][0]) + float(body["after"][0])
if body["operator"][0] == "-":
    ans = float(body["before"][0]) - float(body["after"][0])
if body["operator"][0] == "*":
    ans = float(body["before"][0]) * float(body["after"][0])
if body["operator"][0] == "/":
    ans = float(body["before"][0]) / float(body["after"][0])
print("Content-Type: text/plain; charset=utf-8")
print()
print(ans)
